//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxeltor.StoCombat.Realtime.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CombatLogPath2 {
            get {
                return ((string)(this["CombatLogPath2"]));
            }
            set {
                this["CombatLogPath2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("combatlog*.log")]
        public string CombatLogPathFilePattern2 {
            get {
                return ((string)(this["CombatLogPathFilePattern2"]));
            }
            set {
                this["CombatLogPathFilePattern2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int HowLongBeforeNewCombatInSeconds2 {
            get {
                return ((int)(this["HowLongBeforeNewCombatInSeconds2"]));
            }
            set {
                this["HowLongBeforeNewCombatInSeconds2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyCharacter2 {
            get {
                return ((string)(this["MyCharacter2"]));
            }
            set {
                this["MyCharacter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsEnableInactiveTimeCalculations2 {
            get {
                return ((bool)(this["IsEnableInactiveTimeCalculations2"]));
            }
            set {
                this["IsEnableInactiveTimeCalculations2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MinInActiveInSeconds2 {
            get {
                return ((int)(this["MinInActiveInSeconds2"]));
            }
            set {
                this["MinInActiveInSeconds2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDebugLoggingEnabled2 {
            get {
                return ((bool)(this["IsDebugLoggingEnabled2"]));
            }
            set {
                this["IsDebugLoggingEnabled2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUnrealAnnouncementsEnabled2 {
            get {
                return ((bool)(this["IsUnrealAnnouncementsEnabled2"]));
            }
            set {
                this["IsUnrealAnnouncementsEnabled2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MultiKillWaitInSeconds2 {
            get {
                return ((int)(this["MultiKillWaitInSeconds2"]));
            }
            set {
                this["MultiKillWaitInSeconds2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCalculateAssitedKills2 {
            get {
                return ((bool)(this["IsCalculateAssitedKills2"]));
            }
            set {
                this["IsCalculateAssitedKills2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsIncludeAssistedKillsInAchievements2 {
            get {
                return ((bool)(this["IsIncludeAssistedKillsInAchievements2"]));
            }
            set {
                this["IsIncludeAssistedKillsInAchievements2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int HowOftenParseLogsInSeconds2 {
            get {
                return ((int)(this["HowOftenParseLogsInSeconds2"]));
            }
            set {
                this["HowOftenParseLogsInSeconds2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessKillingSpreeAnnouncements2 {
            get {
                return ((bool)(this["IsProcessKillingSpreeAnnouncements2"]));
            }
            set {
                this["IsProcessKillingSpreeAnnouncements2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessMultiKillAnnouncements2 {
            get {
                return ((bool)(this["IsProcessMultiKillAnnouncements2"]));
            }
            set {
                this["IsProcessMultiKillAnnouncements2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AnnouncementPlaybackVolumePercentage2 {
            get {
                return ((int)(this["AnnouncementPlaybackVolumePercentage2"]));
            }
            set {
                this["AnnouncementPlaybackVolumePercentage2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OverlayWindowContextString2 {
            get {
                return ((string)(this["OverlayWindowContextString2"]));
            }
            set {
                this["OverlayWindowContextString2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessKillingSpreeSplash2 {
            get {
                return ((bool)(this["IsProcessKillingSpreeSplash2"]));
            }
            set {
                this["IsProcessKillingSpreeSplash2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessMultiKillSplash2 {
            get {
                return ((bool)(this["IsProcessMultiKillSplash2"]));
            }
            set {
                this["IsProcessMultiKillSplash2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessMiscSplash2 {
            get {
                return ((bool)(this["IsProcessMiscSplash2"]));
            }
            set {
                this["IsProcessMiscSplash2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProcessMiscAnnouncements2 {
            get {
                return ((bool)(this["IsProcessMiscAnnouncements2"]));
            }
            set {
                this["IsProcessMiscAnnouncements2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AchivementOverlayWindowContextString2 {
            get {
                return ((string)(this["AchivementOverlayWindowContextString2"]));
            }
            set {
                this["AchivementOverlayWindowContextString2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDisplayToolsTab2 {
            get {
                return ((bool)(this["IsDisplayToolsTab2"]));
            }
            set {
                this["IsDisplayToolsTab2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HowLongAfterNoCombatBeforeRemoveFromGridInSeconds2 {
            get {
                return ((int)(this["HowLongAfterNoCombatBeforeRemoveFromGridInSeconds2"]));
            }
            set {
                this["HowLongAfterNoCombatBeforeRemoveFromGridInSeconds2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoCombatRealtimeSettings {
            get {
                return ((string)(this["StoCombatRealtimeSettings"]));
            }
            set {
                this["StoCombatRealtimeSettings"] = value;
            }
        }
    }
}
